[server]
listen_port = 14445
listen_host = "127.0.0.1"

[database]
host="localhost"
port=3306
user="root"
password="ahwuocdz"
db_name="nro_black"
pool_size = 10
max_connections = 20
min_connections = 1
[logging]
level = "info"
file = "logs/app.log"