//! SeaORM Entity. Generated by hand due to sea-orm-cli incompatibility with MariaDB 12.

use crate::models::boss::{BossStages, MapJoin};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "boss_template")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub r#type: String,
    pub gender: i8,
    pub map_join: MapJoin,
    pub seconds_rest: i32,
    pub stages: BossStages,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
