//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "box_item_actions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub template_item_id: i32,
    pub open_mode: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::box_item_drops::Entity")]
    BoxItemDrops,
    #[sea_orm(
        belongs_to = "super::item_template::Entity",
        from = "Column::TemplateItemId",
        to = "super::item_template::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ItemTemplate,
}

impl Related<super::box_item_drops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoxItemDrops.def()
    }
}

impl Related<super::item_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemTemplate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
