//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "box_item_drops")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub box_action_id: i32,
    pub item_template_id: i32,
    pub quantity_min: Option<i32>,
    pub quantity_max: Option<i32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub drop_rate: Option<f32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::box_item_actions::Entity",
        from = "Column::BoxActionId",
        to = "super::box_item_actions::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    BoxItemActions,
    #[sea_orm(has_many = "super::box_item_drop_options::Entity")]
    BoxItemDropOptions,
    #[sea_orm(
        belongs_to = "super::item_template::Entity",
        from = "Column::ItemTemplateId",
        to = "super::item_template::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ItemTemplate,
}

impl Related<super::box_item_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoxItemActions.def()
    }
}

impl Related<super::box_item_drop_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoxItemDropOptions.def()
    }
}

impl Related<super::item_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemTemplate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
