//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "clan_sv2")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "NAME")]
    pub name: String,
    pub slogan: String,
    pub img_id: i32,
    pub power_point: i64,
    pub max_member: i16,
    pub clan_point: i32,
    #[sea_orm(column_name = "LEVEL")]
    pub level: i32,
    #[sea_orm(column_type = "Text")]
    pub members: String,
    pub create_time: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
