//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub news_id: i32,
    pub account_id: Option<i32>,
    pub parent_comment_id: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account::Entity",
        from = "Column::AccountId",
        to = "super::account::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Account,
    #[sea_orm(
        belongs_to = "super::news::Entity",
        from = "Column::NewsId",
        to = "super::news::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    News,
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::news::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::News.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
