//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dhvt_template")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cup: String,
    pub time: String,
    pub gem: i32,
    pub gold: i32,
    pub min_start: i32,
    pub min_limit: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
