//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "giftcode")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub code: String,
    pub count_left: i32,
    pub datecreate: DateTimeUtc,
    pub expired: DateTimeUtc,
    pub is_active: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::giftcode_items::Entity")]
    GiftcodeItems,
}

impl Related<super::giftcode_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcodeItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
