//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "giftcode_item_options")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub giftcode_item_id: i32,
    pub param: i32,
    pub option_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::giftcode_items::Entity",
        from = "Column::GiftcodeItemId",
        to = "super::giftcode_items::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    GiftcodeItems,
    #[sea_orm(
        belongs_to = "super::item_option_template::Entity",
        from = "Column::OptionId",
        to = "super::item_option_template::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    ItemOptionTemplate,
}

impl Related<super::giftcode_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiftcodeItems.def()
    }
}

impl Related<super::item_option_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemOptionTemplate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
