//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "history_giftcode")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub stt: i32,
    pub id_player: i32,
    pub name: String,
    pub id_giftcode: i32,
    pub entry_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
