//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "item_shop_option")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_shop_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub option_id: i32,
    pub param: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::item_option_template::Entity",
        from = "Column::OptionId",
        to = "super::item_option_template::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    ItemOptionTemplate,
    #[sea_orm(
        belongs_to = "super::item_shop::Entity",
        from = "Column::ItemShopId",
        to = "super::item_shop::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    ItemShop,
}

impl Related<super::item_option_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemOptionTemplate.def()
    }
}

impl Related<super::item_shop::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemShop.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
