//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "map_template")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "NAME")]
    pub name: String,
    pub zones: i32,
    pub max_player: i32,
    pub data: String,
    pub r#type: i32,
    pub planet_id: i32,
    pub bg_type: i32,
    pub tile_id: i32,
    pub bg_id: i32,
    #[sea_orm(column_type = "Text")]
    pub waypoints: String,
    #[sea_orm(column_type = "Text")]
    pub mobs: String,
    #[sea_orm(column_type = "Text")]
    pub npcs: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
