//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "market_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub player_id: i32,
    pub item_template_id: i32,
    pub quantity: i32,
    pub sell_price: i64,
    pub time_posted: Option<DateTime>,
    pub status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::item_template::Entity",
        from = "Column::ItemTemplateId",
        to = "super::item_template::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    ItemTemplate,
    #[sea_orm(has_many = "super::market_item_options::Entity")]
    MarketItemOptions,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerId",
        to = "super::player::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Player2,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::PlayerId",
        to = "super::player::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Player1,
}

impl Related<super::item_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemTemplate.def()
    }
}

impl Related<super::market_item_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MarketItemOptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
