//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mob_template")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "TYPE")]
    pub r#type: i32,
    #[sea_orm(column_name = "NAME")]
    pub name: String,
    pub hp: i32,
    pub range_move: i16,
    pub speed: i16,
    pub dart_type: i16,
    pub percent_dame: i16,
    pub percent_tiem_nang: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
