//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "naptien")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub uid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sotien: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub seri: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub loaithe: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub noidung: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tinhtrang: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tranid: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub magioithieu: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
