//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "pet_template")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub r#type: i32,
    pub name: String,
    pub head: i16,
    pub body: i16,
    pub leg: i16,
    pub head_transform: i16,
    pub body_transform: i16,
    pub leg_transform: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
