//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tieude: String,
    #[sea_orm(column_type = "Text")]
    pub noidung: String,
    pub username: String,
    pub created_at: DateTimeUtc,
    pub theloai: i32,
    pub ghimbai: i32,
    pub image: Option<String>,
    pub trangthai: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
