//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "radar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "iconId")]
    pub icon_id: Option<i32>,
    pub rank: Option<i8>,
    pub max: Option<i32>,
    pub r#type: Option<i32>,
    pub gender: Option<i8>,
    pub template: Option<i32>,
    pub item_id: Option<i32>,
    pub bag: Option<i32>,
    pub body: Option<String>,
    pub name: Option<String>,
    pub info: Option<String>,
    pub options: Option<String>,
    pub require: Option<i32>,
    pub require_level: Option<i32>,
    pub aura_id: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
