//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "received_items_options")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub received_item_id: i32,
    pub option_id: i32,
    pub option_value: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::received_items::Entity",
        from = "Column::ReceivedItemId",
        to = "super::received_items::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    ReceivedItems,
}

impl Related<super::received_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReceivedItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
