//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "recharge_card")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub recharge_card_id: i64,
    pub card_detail_id: i32,
    pub account_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub seri: Option<String>,
    #[sea_orm(column_name = "CODE", column_type = "Text", nullable)]
    pub code: Option<String>,
    #[sea_orm(column_name = "Created")]
    pub created: DateTimeUtc,
    #[sea_orm(column_name = "STATUS")]
    pub status: Option<i32>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub trans_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
