//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shop")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub npc_id: i32,
    pub tag_name: Option<String>,
    pub type_shop: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::npc_template::Entity",
        from = "Column::NpcId",
        to = "super::npc_template::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    NpcTemplate,
}

impl Related<super::npc_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NpcTemplate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
