//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shop_ky_gui")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub player_id: i32,
    pub tab: i32,
    pub item_id: i32,
    pub gold: i32,
    pub gem: i32,
    pub quantity: i32,
    #[sea_orm(column_name = "itemOption", column_type = "Text")]
    pub item_option: String,
    #[sea_orm(column_name = "isUpTop")]
    pub is_up_top: i32,
    #[sea_orm(column_name = "isBuy")]
    pub is_buy: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
