//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "skill_template")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub nclass_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "NAME")]
    pub name: String,
    pub max_point: i16,
    pub mana_use_type: i16,
    #[sea_orm(column_name = "TYPE")]
    pub r#type: i16,
    pub icon_id: i32,
    pub dam_info: String,
    pub slot: i32,
    #[sea_orm(column_type = "Text")]
    pub skills: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
