//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "task_sub_template")]
pub struct Model {
    pub task_main_id: i32,
    #[sea_orm(column_name = "NAME")]
    pub name: String,
    pub max_count: i32,
    pub notify: String,
    pub npc_id: i32,
    pub map: i32,
    #[sea_orm(primary_key, auto_increment = true, column_name = "NguyenTanTaiPro")]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
