//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub gateway: String,
    pub transaction_date: DateTimeUtc,
    pub account_number: Option<String>,
    pub sub_account: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount_in: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount_out: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub accumulated: Decimal,
    pub code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_content: Option<String>,
    pub reference_number: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
