[net]
git-fetch-with-cli = true

[build]
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=mold",
  "-Zcodegen-backend=cranelift"
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
c = "check"
r = "run"
b = "build"
br = "build --release"
musl = "build --release --target x86_64-unknown-linux-musl"
win = "build --release --target x86_64-pc-windows-gnu"